### ISSUE TITLE
初次登录时没有输账号，密码页面

### ISSUE THREAD

**Issue by zhexingl** [xiao-cao-x/pixiv_func_mobile#12]
是p站的接口换了吗

**Comment by zhexingl** [comment]
本人已翻墙，未用本地反向代理，这是点击登录后显示页面







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiao-cao-x/pixiv_func_mobile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 下午5:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiao-cao-x/pixiv_func_mobile] 初次登录时没有输账号，密码页面 (Issue #12)





 
是不是WebView加载太慢了

**Comment by xiao-cao-x** [comment]
看不见图片 我现在还可以登录的

**Comment by xiao-cao-x** [comment]
![image](https://user-images.githubusercontent.com/76673990/160584131-24994a51-a5c9-483b-9cba-791d54feaf9a.png)

**Comment by zhexingl** [comment]
那没办法了，是我这边出问题了，或许是因为我的手机系统版本太低了，是安卓版本：6.0.1









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiao-cao-x/pixiv_func_mobile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 下午5:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiao-cao-x/pixiv_func_mobile] 初次登录时没有输账号，密码页面 (Issue #12)

**Comment by xiao-cao-x** [comment]
build.gradle 里 minSdkVersion 是21

**Comment by zhexingl** [comment]
额，什么意思，不懂。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月31日(星期四) 晚上9:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiao-cao-x/pixiv_func_mobile] 初次登录时没有输账号，密码页面 (Issue #12)





 
Closed #12.
