### ISSUE TITLE
preview6版本悄悄收藏功能无效

### ISSUE THREAD

**Issue by ShampooDeng** [xiao-cao-x/pixiv_func_mobile#13]
os: HarmonyOS 2.0.0
version: 1.0.0-preview6

**悄悄收藏**后的插画出现在**公开**收藏中

**Comment by xiao-cao-x** [comment]
前段时间抽离api的时候改了下代码，这个是改出来的bug 我修复了下

**Comment by xiao-cao-x** [comment]
已更新
