### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [xiao-cao-x/pixiv_func_mobile#7]
请问是否可以将应用打包发布到 [F-Droid](https://f-droid.org)？如果你同意的话，我会打包并提交。有一个小问题是 readme 中禁止用于盈利，因此并不符合 F-Droid 对开源的要求。

**Comment by xiao-cao-x** [comment]
可以

**Comment by linsui** [comment]
由于非盈利条款不符合 F-Droid 对开源的要求，所以我没法打包，请问是否可以去掉这个附加条款？谢谢！

**Comment by xiao-cao-x** [comment]
过段添加iOS支持并且项目改名pixiv_func_mobile的时候再修改readme

**Comment by linsui** [comment]
好的，麻烦到时候说一声，谢谢！

**Comment by xiao-cao-x** [comment]
已修改

**Comment by linsui** [comment]
谢谢！

**Comment by xiao-cao-x** [comment]
数字 version code 在Android中是过时(不推荐)的，需要什么样的呢?

**Comment by linsui** [comment]
只要是递增的就行。目前是默认的1。谢谢！

**Comment by linsui** [comment]
Thanks!

**Comment by linsui** [comment]
我在构建的时候有点问题，一直不成功。https://gitlab.com/linsui/fdroiddata/-/jobs/2177293093#L979 可以麻烦看一下吗？谢谢！

**Comment by xiao-cao-x** [comment]
> 我在构建的时候有点问题，一直不成功。https://gitlab.com/linsui/fdroiddata/-/jobs/2177293093#L979 可以麻烦看一下吗？谢谢！

构建不成功很正常
首先需要一个key0.jks
然后AS里Async Now报错的flutter插件需要去他的目录里面是.gradle文件里把有关Test的所有项给删除

**Comment by linsui** [comment]
请问你用的是哪个 Flutter 版本？似乎我用的 2.8.0 版本也不匹配。

**Comment by xiao-cao-x** [comment]
> 请问你用的是哪个 Flutter 版本？似乎我用的 2.8.0 版本也不匹配。

beta频道

**Comment by linsui** [comment]
新的版本构建没问题了 https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11022 谢谢！
